### ISSUE TITLE
Data too long for column 'vehicle' at row 1

### ISSUE THREAD

**Issue by IamCodyy** [najeetpie/nass_serverstore#1]
The issue happened when I was testing the plate changer.

QBCore
oxMySQL

The "vehicle" column is trying to store the vehicle mods.

`[      script:oxmysql] UPDATE player_vehicles SET plate = ?, vehicle = ? WHERE plate = ? ["TIFAPIMP","{\"modXenon\":false,\"modDashboard\":-1,\"tireBurstCompletely\":{\"5\":false,\"0\":false,\"1\":false,\"2\":false,\"3\":false,\"4\":false},\"bodyHealth\":1000.0592475178704,\"modSteeringWheel\":-1,\"extras\":[],\"oilLevel\":4.76596940834568,\"modLivery\":-1,\"plate\":\"TIFAPIMP\",\"modEngine\":3,\"modRearBumper\":-1,\"tireBurstState\":{\"5\":false,\"0\":false,\"1\":false,\"2\":false,\"3\":false,\"4\":false},\"modGrille\":-1,\"modCustomTiresR\":false,\"modRoof\":-1,\"doorStatus\":{\"5\":false,\"0\":false,\"1\":false,\"2\":false,\"3\":false,\"4\":false},\"wheels\":0,\"dirtLevel\":0.0,\"modPlateHolder\":-1,\"modTransmission\":2,\"neonColor\":[255,0,255],\"modKit17\":-1,\"modVanityPlate\":-1,\"color1Coat\":7,\"tyreSmokeColor\":[255,255,255],\"headlightColor\":255,\"color1\":0,\"modSpoilers\":-1,\"modHydrolic\":-1,\"tankHealth\":4000.2369900714818,\"modRightFender\":-1,\"liveryRoof\":-1,\"modFrontBumper\":-1,\"modArchCover\":-1,\"modDial\":-1,\"modAirFilter\":-1,\"wheelColor\":0,\"modTrimA\":-1,\"fuelLevel\":79.43282347242814,\"tireHealth\":{\"1\":1000.0,\"2\":1000.0,\"3\":1000.0,\"0\":1000.0},\"xenonColor\":255,\"modFrame\":-1,\"dashboardColor\":0,\"modTurbo\":1,\"modSeats\":-1,\"modSmokeEnabled\":false,\"modSuspension\":3,\"modKit19\":-1,\"modOrnaments\":-1,\"windowStatus\":{\"5\":false,\"6\":true,\"7\":true,\"0\":true,\"1\":true,\"2\":true,\"3\":true,\"4\":false},\"modSideSkirt\":-1,\"modSpeakers\":-1,\"color2Coat\":7,\"neonEnabled\":[false,false,false,false],\"modKit49\":-1,\"modEngineBlock\":-1,\"modAPlate\":-1,\"modTrunk\":-1,\"modFender\":-1,\"modCustomTiresF\":false,\"plateIndex\":4,\"model\":-954171800,\"modHood\":-1,\"wheelSize\":1.0,\"color2\":0,\"wheelWidth\":1.0,\"windowTint\":1,\"modKit47\":-1,\"modShifterLeavers\":-1,\"modExhaust\":-1,\"modTrimB\":-1,\"modStruts\":-1,\"modHorns\":-1,\"engineHealth\":1000.0592475178704,\"modArmor\":-1,\"modWindows\":-1,\"interiorColor\":0,\"modBrakes\":2,\"modDoorSpeaker\":-1,\"modFrontWheels\":-1,\"modAerials\":-1,\"modTank\":-1,\"modBackWheels\":-1,\"modKit21\":-1,\"pearlescentColor\":0}","MPWW 531"]`

**Comment by najeetpie** [comment]
Issue was fixed in the latest commit

**Comment by IamCodyy** [comment]
Works, thanks. Another issue: You need to hotwire your own car after the plate changes!

**Comment by najeetpie** [comment]
That's with your keysystem, you need to add keys the vehicle when the player changes the plate.

**Comment by IamCodyy** [comment]
I'm using default vehiclekeys, but I will make the modification.
