### ISSUE TITLE
Purchased packages doubling in the database.

### ISSUE THREAD

**Issue by IamCodyy** [najeetpie/nass_serverstore#3]
Purchased packages are being registered into the database.

I'm using the correct command
`purchase_package_tebex {"transid":"{transaction}", "packagename":"{packageName}"}`

In the database the package names show as ["Test 1", "Test 1"]

**Comment by najeetpie** [comment]
You have the command sending twice in your tebex store. Double check the package and make sure it only sends once.

**Comment by IamCodyy** [comment]
> You have the command sending twice in your tebex store. Double check the package and make sure it only sends once.

![image](https://github.com/najeetpie/nass_serverstore/assets/6721888/cfba5378-318b-4291-861e-cc5f68fe6e67)

![image](https://github.com/najeetpie/nass_serverstore/assets/6721888/ad4ac5a7-4058-436c-a498-7b319c682bf0)

This appears to be sending once.
